export const init_data = [
    {
      "Station": "Bangwela",
      "Central": 0,
      "Copperbelt": 0,
      "Eastern": 0,
      "Luapula": 78,
      "Lusaka": 0,
      "Muchinga": 0,
      "North-Western": 0,
      "Northern": 0,
      "Southern": 0,
      "Western": 0,
      "PROVINCE TOTAL": 78,
      "Chibombo": 0,
      "Chinsali": 0,
      "Chipata": 0,
      "Isoka": 0,
      "Kabwe": 0,
      "Kafue": 0,
      "Kalabo": 0,
      "Kaoma": 0,
      "Kapiri Mposhi": 0,
      "Kasama": 0,
      "Kawambwa": 1,
      "Kitwe": 0,
      "Livingstone": 0,
      "Luanshya": 0,
      "Lukulu": 0,
      "Lusaka district": 0,
      "Mafinga": 0,
      "Mansa": 3,
      "Mazabuka": 0,
      "Mkushi": 0,
      "Mongu": 0,
      "Mpika": 0,
      "Mungwi": 0,
      "Nakonde": 0,
      "Nchelenge": 0,
      "Ndola": 0,
      "Petauke": 0,
      "Samfya": 74,
      "Senanga": 0,
      "Serenje": 0,
      "Solwezi": 0,
      "DISTRICTS TOTAL": 78,
      "Female": 56,
      "Male": 22,
      "GENDER TOTAL": 78,
      "15 – 18": 8,
      "19 – 24": 27,
      "25 – 34": 23,
      "35 – 44": 10,
      "45+": 10,
      "AGE RANGE TOTAL": 78,
      "Rural": 49,
      "Urban": 29,
      "AREA TYPE TOTAL": 78
    },
    {
      "Station": "Chimwemwe",
      "Central": 0,
      "Copperbelt": 27,
      "Eastern": 0,
      "Luapula": 0,
      "Lusaka": 0,
      "Muchinga": 0,
      "North-Western": 0,
      "Northern": 0,
      "Southern": 0,
      "Western": 0,
      "PROVINCE TOTAL": 27,
      "Chibombo": 0,
      "Chinsali": 0,
      "Chipata": 0,
      "Isoka": 0,
      "Kabwe": 0,
      "Kafue": 0,
      "Kalabo": 0,
      "Kaoma": 0,
      "Kapiri Mposhi": 0,
      "Kasama": 0,
      "Kawambwa": 0,
      "Kitwe": 1,
      "Livingstone": 0,
      "Luanshya": 6,
      "Lukulu": 0,
      "Lusaka district": 0,
      "Mafinga": 0,
      "Mansa": 0,
      "Mazabuka": 0,
      "Mkushi": 0,
      "Mongu": 0,
      "Mpika": 0,
      "Mungwi": 0,
      "Nakonde": 0,
      "Nchelenge": 0,
      "Ndola": 20,
      "Petauke": 0,
      "Samfya": 0,
      "Senanga": 0,
      "Serenje": 0,
      "Solwezi": 0,
      "DISTRICTS TOTAL": 27,
      "Female": 9,
      "Male": 18,
      "GENDER TOTAL": 27,
      "15 – 18": 0,
      "19 – 24": 10,
      "25 – 34": 11,
      "35 – 44": 2,
      "45+": 4,
      "AGE RANGE TOTAL": 27,
      "Rural": 4,
      "Urban": 23,
      "AREA TYPE TOTAL": 27
    },
    {
      "Station": "FCC Solwezi",
      "Central": 0,
      "Copperbelt": 0,
      "Eastern": 0,
      "Luapula": 0,
      "Lusaka": 0,
      "Muchinga": 0,
      "North-Western": 8,
      "Northern": 0,
      "Southern": 0,
      "Western": 0,
      "PROVINCE TOTAL": 8,
      "Chibombo": 0,
      "Chinsali": 0,
      "Chipata": 0,
      "Isoka": 0,
      "Kabwe": 0,
      "Kafue": 0,
      "Kalabo": 0,
      "Kaoma": 0,
      "Kapiri Mposhi": 0,
      "Kasama": 0,
      "Kawambwa": 0,
      "Kitwe": 0,
      "Livingstone": 0,
      "Luanshya": 0,
      "Lukulu": 0,
      "Lusaka district": 0,
      "Mafinga": 0,
      "Mansa": 0,
      "Mazabuka": 0,
      "Mkushi": 0,
      "Mongu": 0,
      "Mpika": 0,
      "Mungwi": 0,
      "Nakonde": 0,
      "Nchelenge": 0,
      "Ndola": 0,
      "Petauke": 0,
      "Samfya": 0,
      "Senanga": 0,
      "Serenje": 0,
      "Solwezi": 8,
      "DISTRICTS TOTAL": 8,
      "Female": 4,
      "Male": 4,
      "GENDER TOTAL": 8,
      "15 – 18": 0,
      "19 – 24": 1,
      "25 – 34": 4,
      "35 – 44": 3,
      "45+": 0,
      "AGE RANGE TOTAL": 8,
      "Rural": 1,
      "Urban": 7,
      "AREA TYPE TOTAL": 8
    },
    {
      "Station": "Hot",
      "Central": 1,
      "Copperbelt": 0,
      "Eastern": 0,
      "Luapula": 0,
      "Lusaka": 6,
      "Muchinga": 0,
      "North-Western": 0,
      "Northern": 0,
      "Southern": 0,
      "Western": 0,
      "PROVINCE TOTAL": 7,
      "Chibombo": 0,
      "Chinsali": 0,
      "Chipata": 0,
      "Isoka": 0,
      "Kabwe": 1,
      "Kafue": 0,
      "Kalabo": 0,
      "Kaoma": 0,
      "Kapiri Mposhi": 0,
      "Kasama": 0,
      "Kawambwa": 0,
      "Kitwe": 0,
      "Livingstone": 0,
      "Luanshya": 0,
      "Lukulu": 0,
      "Lusaka district": 6,
      "Mafinga": 0,
      "Mansa": 0,
      "Mazabuka": 0,
      "Mkushi": 0,
      "Mongu": 0,
      "Mpika": 0,
      "Mungwi": 0,
      "Nakonde": 0,
      "Nchelenge": 0,
      "Ndola": 0,
      "Petauke": 0,
      "Samfya": 0,
      "Senanga": 0,
      "Serenje": 0,
      "Solwezi": 0,
      "DISTRICTS TOTAL": 7,
      "Female": 3,
      "Male": 4,
      "GENDER TOTAL": 7,
      "15 – 18": 0,
      "19 – 24": 3,
      "25 – 34": 3,
      "35 – 44": 1,
      "45+": 0,
      "AGE RANGE TOTAL": 7,
      "Rural": 0,
      "Urban": 7,
      "AREA TYPE TOTAL": 7
    },
    {
      "Station": "K FM",
      "Central": 0,
      "Copperbelt": 0,
      "Eastern": 0,
      "Luapula": 79,
      "Lusaka": 0,
      "Muchinga": 0,
      "North-Western": 0,
      "Northern": 0,
      "Southern": 0,
      "Western": 0,
      "PROVINCE TOTAL": 79,
      "Chibombo": 0,
      "Chinsali": 0,
      "Chipata": 0,
      "Isoka": 0,
      "Kabwe": 0,
      "Kafue": 0,
      "Kalabo": 0,
      "Kaoma": 0,
      "Kapiri Mposhi": 0,
      "Kasama": 0,
      "Kawambwa": 12,
      "Kitwe": 0,
      "Livingstone": 0,
      "Luanshya": 0,
      "Lukulu": 0,
      "Lusaka district": 0,
      "Mafinga": 0,
      "Mansa": 57,
      "Mazabuka": 0,
      "Mkushi": 0,
      "Mongu": 0,
      "Mpika": 0,
      "Mungwi": 0,
      "Nakonde": 0,
      "Nchelenge": 5,
      "Ndola": 0,
      "Petauke": 0,
      "Samfya": 5,
      "Senanga": 0,
      "Serenje": 0,
      "Solwezi": 0,
      "DISTRICTS TOTAL": 79,
      "Female": 52,
      "Male": 27,
      "GENDER TOTAL": 79,
      "15 – 18": 12,
      "19 – 24": 26,
      "25 – 34": 23,
      "35 – 44": 11,
      "45+": 7,
      "AGE RANGE TOTAL": 79,
      "Rural": 62,
      "Urban": 17,
      "AREA TYPE TOTAL": 79
    },
    {
      "Station": "KNC",
      "Central": 179,
      "Copperbelt": 0,
      "Eastern": 0,
      "Luapula": 0,
      "Lusaka": 0,
      "Muchinga": 0,
      "North-Western": 0,
      "Northern": 0,
      "Southern": 0,
      "Western": 0,
      "PROVINCE TOTAL": 179,
      "Chibombo": 0,
      "Chinsali": 0,
      "Chipata": 0,
      "Isoka": 0,
      "Kabwe": 62,
      "Kafue": 0,
      "Kalabo": 0,
      "Kaoma": 0,
      "Kapiri Mposhi": 77,
      "Kasama": 0,
      "Kawambwa": 0,
      "Kitwe": 0,
      "Livingstone": 0,
      "Luanshya": 0,
      "Lukulu": 0,
      "Lusaka district": 0,
      "Mafinga": 0,
      "Mansa": 0,
      "Mazabuka": 0,
      "Mkushi": 39,
      "Mongu": 0,
      "Mpika": 0,
      "Mungwi": 0,
      "Nakonde": 0,
      "Nchelenge": 0,
      "Ndola": 0,
      "Petauke": 0,
      "Samfya": 0,
      "Senanga": 0,
      "Serenje": 1,
      "Solwezi": 0,
      "DISTRICTS TOTAL": 179,
      "Female": 129,
      "Male": 50,
      "GENDER TOTAL": 179,
      "15 – 18": 28,
      "19 – 24": 53,
      "25 – 34": 64,
      "35 – 44": 20,
      "45+": 14,
      "AGE RANGE TOTAL": 179,
      "Rural": 81,
      "Urban": 98,
      "AREA TYPE TOTAL": 179
    },
    {
      "Station": "Luapula",
      "Central": 0,
      "Copperbelt": 0,
      "Eastern": 0,
      "Luapula": 34,
      "Lusaka": 0,
      "Muchinga": 0,
      "North-Western": 0,
      "Northern": 0,
      "Southern": 0,
      "Western": 0,
      "PROVINCE TOTAL": 34,
      "Chibombo": 0,
      "Chinsali": 0,
      "Chipata": 0,
      "Isoka": 0,
      "Kabwe": 0,
      "Kafue": 0,
      "Kalabo": 0,
      "Kaoma": 0,
      "Kapiri Mposhi": 0,
      "Kasama": 0,
      "Kawambwa": 0,
      "Kitwe": 0,
      "Livingstone": 0,
      "Luanshya": 0,
      "Lukulu": 0,
      "Lusaka district": 0,
      "Mafinga": 0,
      "Mansa": 1,
      "Mazabuka": 0,
      "Mkushi": 0,
      "Mongu": 0,
      "Mpika": 0,
      "Mungwi": 0,
      "Nakonde": 0,
      "Nchelenge": 30,
      "Ndola": 0,
      "Petauke": 0,
      "Samfya": 3,
      "Senanga": 0,
      "Serenje": 0,
      "Solwezi": 0,
      "DISTRICTS TOTAL": 34,
      "Female": 19,
      "Male": 15,
      "GENDER TOTAL": 34,
      "15 – 18": 7,
      "19 – 24": 7,
      "25 – 34": 12,
      "35 – 44": 6,
      "45+": 2,
      "AGE RANGE TOTAL": 34,
      "Rural": 27,
      "Urban": 7,
      "AREA TYPE TOTAL": 34
    },
    {
      "Station": "Luswepo",
      "Central": 0,
      "Copperbelt": 0,
      "Eastern": 0,
      "Luapula": 0,
      "Lusaka": 0,
      "Muchinga": 0,
      "North-Western": 0,
      "Northern": 4,
      "Southern": 0,
      "Western": 0,
      "PROVINCE TOTAL": 4,
      "Chibombo": 0,
      "Chinsali": 0,
      "Chipata": 0,
      "Isoka": 0,
      "Kabwe": 0,
      "Kafue": 0,
      "Kalabo": 0,
      "Kaoma": 0,
      "Kapiri Mposhi": 0,
      "Kasama": 3,
      "Kawambwa": 0,
      "Kitwe": 0,
      "Livingstone": 0,
      "Luanshya": 0,
      "Lukulu": 0,
      "Lusaka district": 0,
      "Mafinga": 0,
      "Mansa": 0,
      "Mazabuka": 0,
      "Mkushi": 0,
      "Mongu": 0,
      "Mpika": 0,
      "Mungwi": 1,
      "Nakonde": 0,
      "Nchelenge": 0,
      "Ndola": 0,
      "Petauke": 0,
      "Samfya": 0,
      "Senanga": 0,
      "Serenje": 0,
      "Solwezi": 0,
      "DISTRICTS TOTAL": 4,
      "Female": 4,
      "Male": 0,
      "GENDER TOTAL": 4,
      "15 – 18": 1,
      "19 – 24": 2,
      "25 – 34": 1,
      "35 – 44": 0,
      "45+": 0,
      "AGE RANGE TOTAL": 4,
      "Rural": 4,
      "Urban": 0,
      "AREA TYPE TOTAL": 4
    },
    {
      "Station": "Mazabuka",
      "Central": 0,
      "Copperbelt": 0,
      "Eastern": 0,
      "Luapula": 0,
      "Lusaka": 0,
      "Muchinga": 0,
      "North-Western": 0,
      "Northern": 0,
      "Southern": 5,
      "Western": 0,
      "PROVINCE TOTAL": 5,
      "Chibombo": 0,
      "Chinsali": 0,
      "Chipata": 0,
      "Isoka": 0,
      "Kabwe": 0,
      "Kafue": 0,
      "Kalabo": 0,
      "Kaoma": 0,
      "Kapiri Mposhi": 0,
      "Kasama": 0,
      "Kawambwa": 0,
      "Kitwe": 0,
      "Livingstone": 0,
      "Luanshya": 0,
      "Lukulu": 0,
      "Lusaka district": 0,
      "Mafinga": 0,
      "Mansa": 0,
      "Mazabuka": 5,
      "Mkushi": 0,
      "Mongu": 0,
      "Mpika": 0,
      "Mungwi": 0,
      "Nakonde": 0,
      "Nchelenge": 0,
      "Ndola": 0,
      "Petauke": 0,
      "Samfya": 0,
      "Senanga": 0,
      "Serenje": 0,
      "Solwezi": 0,
      "DISTRICTS TOTAL": 5,
      "Female": 3,
      "Male": 2,
      "GENDER TOTAL": 5,
      "15 – 18": 0,
      "19 – 24": 1,
      "25 – 34": 2,
      "35 – 44": 1,
      "45+": 1,
      "AGE RANGE TOTAL": 5,
      "Rural": 2,
      "Urban": 3,
      "AREA TYPE TOTAL": 5
    },
    {
      "Station": "Radio 1",
      "Central": 147,
      "Copperbelt": 22,
      "Eastern": 11,
      "Luapula": 40,
      "Lusaka": 4,
      "Muchinga": 53,
      "North-Western": 17,
      "Northern": 33,
      "Southern": 7,
      "Western": 54,
      "PROVINCE TOTAL": 388,
      "Chibombo": 1,
      "Chinsali": 10,
      "Chipata": 5,
      "Isoka": 3,
      "Kabwe": 14,
      "Kafue": 3,
      "Kalabo": 21,
      "Kaoma": 14,
      "Kapiri Mposhi": 67,
      "Kasama": 17,
      "Kawambwa": 4,
      "Kitwe": 19,
      "Livingstone": 5,
      "Luanshya": 3,
      "Lukulu": 1,
      "Lusaka district": 1,
      "Mafinga": 1,
      "Mansa": 14,
      "Mazabuka": 2,
      "Mkushi": 33,
      "Mongu": 7,
      "Mpika": 26,
      "Mungwi": 16,
      "Nakonde": 13,
      "Nchelenge": 9,
      "Ndola": 0,
      "Petauke": 6,
      "Samfya": 13,
      "Senanga": 11,
      "Serenje": 32,
      "Solwezi": 17,
      "DISTRICTS TOTAL": 388,
      "Female": 248,
      "Male": 140,
      "GENDER TOTAL": 388,
      "15 – 18": 50,
      "19 – 24": 94,
      "25 – 34": 120,
      "35 – 44": 88,
      "45+": 36,
      "AGE RANGE TOTAL": 388,
      "Rural": 240,
      "Urban": 148,
      "AREA TYPE TOTAL": 388
    },
    {
      "Station": "Sun FM",
      "Central": 8,
      "Copperbelt": 0,
      "Eastern": 0,
      "Luapula": 0,
      "Lusaka": 0,
      "Muchinga": 0,
      "North-Western": 0,
      "Northern": 0,
      "Southern": 0,
      "Western": 0,
      "PROVINCE TOTAL": 8,
      "Chibombo": 0,
      "Chinsali": 0,
      "Chipata": 0,
      "Isoka": 0,
      "Kabwe": 1,
      "Kafue": 0,
      "Kalabo": 0,
      "Kaoma": 0,
      "Kapiri Mposhi": 6,
      "Kasama": 0,
      "Kawambwa": 0,
      "Kitwe": 0,
      "Livingstone": 0,
      "Luanshya": 0,
      "Lukulu": 0,
      "Lusaka district": 0,
      "Mafinga": 0,
      "Mansa": 0,
      "Mazabuka": 0,
      "Mkushi": 1,
      "Mongu": 0,
      "Mpika": 0,
      "Mungwi": 0,
      "Nakonde": 0,
      "Nchelenge": 0,
      "Ndola": 0,
      "Petauke": 0,
      "Samfya": 0,
      "Senanga": 0,
      "Serenje": 0,
      "Solwezi": 0,
      "DISTRICTS TOTAL": 8,
      "Female": 7,
      "Male": 1,
      "GENDER TOTAL": 8,
      "15 – 18": 4,
      "19 – 24": 3,
      "25 – 34": 1,
      "35 – 44": 0,
      "45+": 0,
      "AGE RANGE TOTAL": 8,
      "Rural": 4,
      "Urban": 4,
      "AREA TYPE TOTAL": 8
    },
    {
      "Station": "Unza",
      "Central": 0,
      "Copperbelt": 0,
      "Eastern": 0,
      "Luapula": 0,
      "Lusaka": 1,
      "Muchinga": 0,
      "North-Western": 0,
      "Northern": 0,
      "Southern": 0,
      "Western": 0,
      "PROVINCE TOTAL": 1,
      "Chibombo": 0,
      "Chinsali": 0,
      "Chipata": 0,
      "Isoka": 0,
      "Kabwe": 0,
      "Kafue": 0,
      "Kalabo": 0,
      "Kaoma": 0,
      "Kapiri Mposhi": 0,
      "Kasama": 0,
      "Kawambwa": 0,
      "Kitwe": 0,
      "Livingstone": 0,
      "Luanshya": 0,
      "Lukulu": 0,
      "Lusaka district": 1,
      "Mafinga": 0,
      "Mansa": 0,
      "Mazabuka": 0,
      "Mkushi": 0,
      "Mongu": 0,
      "Mpika": 0,
      "Mungwi": 0,
      "Nakonde": 0,
      "Nchelenge": 0,
      "Ndola": 0,
      "Petauke": 0,
      "Samfya": 0,
      "Senanga": 0,
      "Serenje": 0,
      "Solwezi": 0,
      "DISTRICTS TOTAL": 1,
      "Female": 0,
      "Male": 1,
      "GENDER TOTAL": 1,
      "15 – 18": 0,
      "19 – 24": 0,
      "25 – 34": 1,
      "35 – 44": 0,
      "45+": 0,
      "AGE RANGE TOTAL": 1,
      "Rural": 0,
      "Urban": 1,
      "AREA TYPE TOTAL": 1
    },
    {
      "Station": "Zambezi",
      "Central": 0,
      "Copperbelt": 0,
      "Eastern": 0,
      "Luapula": 0,
      "Lusaka": 0,
      "Muchinga": 0,
      "North-Western": 0,
      "Northern": 0,
      "Southern": 5,
      "Western": 0,
      "PROVINCE TOTAL": 5,
      "Chibombo": 0,
      "Chinsali": 0,
      "Chipata": 0,
      "Isoka": 0,
      "Kabwe": 0,
      "Kafue": 0,
      "Kalabo": 0,
      "Kaoma": 0,
      "Kapiri Mposhi": 0,
      "Kasama": 0,
      "Kawambwa": 0,
      "Kitwe": 0,
      "Livingstone": 5,
      "Luanshya": 0,
      "Lukulu": 0,
      "Lusaka district": 0,
      "Mafinga": 0,
      "Mansa": 0,
      "Mazabuka": 0,
      "Mkushi": 0,
      "Mongu": 0,
      "Mpika": 0,
      "Mungwi": 0,
      "Nakonde": 0,
      "Nchelenge": 0,
      "Ndola": 0,
      "Petauke": 0,
      "Samfya": 0,
      "Senanga": 0,
      "Serenje": 0,
      "Solwezi": 0,
      "DISTRICTS TOTAL": 5,
      "Female": 4,
      "Male": 1,
      "GENDER TOTAL": 5,
      "15 – 18": 0,
      "19 – 24": 3,
      "25 – 34": 1,
      "35 – 44": 1,
      "45+": 0,
      "AGE RANGE TOTAL": 5,
      "Rural": 0,
      "Urban": 5,
      "AREA TYPE TOTAL": 5
    }
  ]